In [32]:
import numpy as np
import tensorflow as tf

# index to characteristic 으로 각각의 알파벳에 대해  one hot encoding을 하기 위한 코드임.

In [33]:
idx2char = ['h','i','e','l','o']
#teach hello : hihell->ihello  (hi hello)
#x_data = [[0,1,0,2,3,3]]#hihell
y_data = [[1,0,2,3,3,4]] #ihello

0 = h, 1 = i, 2 = e,  3 = l, 4 = o 로 구성

In [34]:
num_classes = 5
#h,i,e,l,o 5개로 분류하는것.
input_dim = 5 #one-hot size, same as hidden_size to directly predict one-hot
sequence_length = 6 #ihell=6
learning_rate = 0.1

In [35]:
x_one_hot = np.array([[[1,0,0,0,0], #h0
                      [0,1,0,0,0], #i1
                      [1,0,0,0,0], #h0
                      [0,0,1,0,0], #e2
                      [0,0,0,1,0], #l3 
                      [0,0,0,0,1]]],#l3 
                    dtype = np.float32)
#학습하기 위한 x_data를 원핫인코딩한 값으로 정해주는 것.
#hi hell을 x_data로 넣어주는 중
#직접하는 코드인듯??

In [36]:
y_one_hot = tf.keras.utils.to_categorical(y_data,num_classes=num_classes)
#y_data를 원핫인코딩해주는 코드임. 더깔끔하게 하는 코드인듯.(keras에서 지원해주는 원핫인코딩)
#정수를 이진 클래스 행렬로 변환함
print(x_one_hot.shape)
print(y_one_hot.shape)

(1, 6, 5)
(1, 6, 5)


In [37]:
tf.model = tf.keras.Sequential()

In [38]:
cell = tf.keras.layers.LSTMCell(units=num_classes,input_shape=(sequence_length,input_dim))
#LSTM으로 5개의 분류, 6행 5열로  input_data를 정렬해주는 것을 의미.

In [39]:
tf.model.add(tf.keras.layers.RNN(cell=cell, return_sequences=True))
#RNN으로  LSTM cell을 정해주고 마지막 명령어로  time sequential(시간순서로)한 데이터 임을 선언해줌.

In [40]:
tf.model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units=num_classes,activation='softmax')))
#모델의 layer을 설정해주는 부분으로, 기존에는 tf.keras.layers(!!)이런식으로 정리되었는데
#TimeDistributed를 추가시켜줌.
#classes를 5개로 선언하고, softmax를 사용한코드

RNN, LSTM에서는 더이상 Relu를 사용하지 않음.
Relu는 0이상에 값에서는 y=x가 나오기 때문에 1이상 값이 나올경우 발산할 확률이 높음(거의다 발산함.)
따라서 output의 값을 -1~1사이로 해주기 위한 softmax또는 tanh을 주로 사용함.

In [42]:
tf.model.compile(loss='categorical_crossentropy',optimizer=tf.keras.optimizers.Adam(lr=learning_rate),metrics=['accuracy'])
#컴파일이란 어떤 언어 코드를 다른 언어로 바꿔주는 과정임@/
#언어를 바꿔주는 과정임.

In [43]:
tf.model.fit(x_one_hot,y_one_hot,epochs=50)
tf.model.summary()

Epoch 1/50
1/1 [==============================] - 1s 1s/step - loss: 1.6104 - accuracy: 0.3333
Epoch 2/50
1/1 [==============================] - 0s 5ms/step - loss: 1.5232 - accuracy: 0.3333
Epoch 3/50
1/1 [==============================] - 0s 6ms/step - loss: 1.4315 - accuracy: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 10ms/step - loss: 1.3114 - accuracy: 0.3333
Epoch 5/50
1/1 [==============================] - 0s 10ms/step - loss: 1.1670 - accuracy: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 7ms/step - loss: 1.0218 - accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 10ms/step - loss: 0.8872 - accuracy: 0.6667
Epoch 8/50
1/1 [==============================] - 0s 4ms/step - loss: 0.7608 - accuracy: 0.8333
Epoch 9/50
1/1 [==============================] - 0s 14ms/step - loss: 0.6523 - accuracy: 0.8333
Epoch 10/50
1/1 [==============================] - 0s 11ms/step - loss: 0.5650 - accuracy: 0.8333
Epoch 11/50
1/1 [==================

In [44]:
predictions =  tf.model.predict(x_one_hot)
for i,prediction in enumerate(predictions):
    print(prediction)
    result_str=[idx2char[c]for c in np.argmax(prediction,axis=1)]
    print("\tPrediction str:",''.join(result_str))

[[1.6422161e-03 9.9173892e-01 6.1305999e-03 6.6431016e-06 4.8164322e-04]
 [9.9863040e-01 6.2729110e-04 2.4510198e-04 4.6984779e-04 2.7407155e-05]
 [9.4573779e-06 4.1620005e-03 9.9579430e-01 3.2813172e-05 1.4062542e-06]
 [2.0599045e-04 6.4278065e-06 2.5202460e-05 9.9970883e-01 5.3513922e-05]
 [2.3161967e-06 1.1132944e-06 3.4926798e-06 9.9985886e-01 1.3424028e-04]
 [9.1339438e-04 2.3375126e-03 3.0832481e-07 2.7096889e-04 9.9647778e-01]]
	Prediction str: ihello


In [45]:
predictions
#예측

array([[[1.6422161e-03, 9.9173892e-01, 6.1305999e-03, 6.6431016e-06,
         4.8164322e-04],
        [9.9863040e-01, 6.2729110e-04, 2.4510198e-04, 4.6984779e-04,
         2.7407155e-05],
        [9.4573779e-06, 4.1620005e-03, 9.9579430e-01, 3.2813172e-05,
         1.4062542e-06],
        [2.0599045e-04, 6.4278065e-06, 2.5202460e-05, 9.9970883e-01,
         5.3513922e-05],
        [2.3161967e-06, 1.1132944e-06, 3.4926798e-06, 9.9985886e-01,
         1.3424028e-04],
        [9.1339438e-04, 2.3375126e-03, 3.0832481e-07, 2.7096889e-04,
         9.9647778e-01]]], dtype=float32)

argmax 란 arugment of the maxima 의 축약형
최대 값에 해당하는 index 즉 위치를 알려줌. 
(argmin도 있음 이거는 최소값의 위치 알려줌.)